- lib/puppet_litmus/rake_tasks.rb
Updating rake task usage examples.
> (maint) - Update Rake task usage example for litmus

- lib/puppet_litmus/serverspec.rb
This PR is to try and utilise more of boltspec in bolt and to better name some of the helper functions.
> (FM-7470) change method names, use upload_file

- lib/puppet_litmus/rake_tasks.rb
This is an experimental feature for the use of internal Puppet employees.
In theory it should let you install the latest pe build for testing on a machine.
Please note this is indeed experimental, relies on you being internal for authentication and will be for an all-in-one setup.
This does not introduce complex setups like master-agent.
> Addition of pe_install rake task

- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
also check for nodes before running anything on them
> (FM-8185) Use spinner when provisioning 

- lib/puppet_litmus/rake_tasks.rb
Prior to this commit running `litmus:acceptance:parallel` from a windows
node failed during the call to run the tests per target host. This was
due to the command string prepending the target host as an environment
variable before the execution, which does not work on Windows.
This commit updates the payloads creation to standardize the exec call
and enable passing an options hash, including environment variables to
send to the Open3 call.
This enables execution from a Windows node.
Co-authored-by: Glenn Sarti <glenn.sarti@outlook.com>
> (FM-8273) Enable parallel acceptance from Windows

- lib/puppet_litmus/inventory_manipulation.rb
- spec/lib/puppet_litmus/inventory_manipulation_spec.rb
Changes are added to handle the empty feature hash. Unit test cases are added to verify the changes.
> (minor fix for addfeaturegroup function)

- CHANGELOG.md
- lib/puppet_litmus/version.rb
> (maint) release_prep_0.6.0

- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
Adds a command which can be used to run a script file against a target
host.
> (FM-8284) Add bolt_run_script command

- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
Following changes are made to the function run_bolt_task
- Added unit testcase to verify the success and failure conditions
- Added version and _error to verify the task output for the package module
- Added expect_failure options
> FM-8286 run_bolt_task returns bolt result object

- lib/puppet_litmus/rake_tasks.rb
the text of spec_prep got garbled by the spinner, this starts the spinner after spec_prep
> (FM-8299) spinner runs after spec_prep in provision

- lib/puppet_litmus/inventory_manipulation.rb
Request for a review.
This is to prevent multiple updates to the file.
> (minor update) fix multiple update to inventoryfile

- lib/puppet_litmus/rake_tasks.rb
Fixes case where path contains spaces
> (bugfix) Use quote around upload path

- lib/puppet_litmus/inventory_manipulation.rb
- spec/lib/puppet_litmus/inventory_manipulation_spec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
This commit adds functionality to add/remove features from the bolt
inventory by node instead of group.
> (feat) Enable manipulating inventory features by node

- lib/puppet_litmus/serverspec.rb
> MODULES-9729 update exit code for nil cases

- CHANGELOG.md
- lib/puppet_litmus/version.rb
> (FM-8451)Release Prep 0.8.1

- lib/puppet_litmus/version.rb
> FM-8462 Release Prep 0.8.2

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Waiting for the module tests to finish execution
> (maint) release prep 0.12.0

- CHANGELOG.md
- lib/puppet_litmus/version.rb
https://github.com/puppetlabs/puppetlabs-motd/pull/266 -Success
https://github.com/puppetlabs/puppetlabs-package/pull/166 - Success
https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/105 - Failed on appveyor
Release check results
motd
scheduled_task
package
> (maint) release prep 0.13.0

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Travis running clean on all 3 modules
https://github.com/puppetlabs/puppetlabs-motd/pull/270
https://github.com/puppetlabs/puppetlabs-package/pull/169
https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/111
Releasechecks also succeed
`
+---------------------------+----------+------------------------------------------------------------------------------------------------------------+------+
--
\|                                                                   Module Test Results                                                                    \|
+---------------------------+----------+------------------------------------------------------------------------------------------------------------+------+
\| Module                    \| Status   \| Result …
> (maint) Releaseprep 0.13.1

- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
The addition of this to existing rake tasks will happen in another PR
> (feat) new rake task to check nodes are available

- CHANGELOG.md
- lib/puppet_litmus/version.rb
> (MODULES-10479) Release prep 0.15.0

- CHANGELOG.md
Request for a review.
Fix for the changelog(missing 0.14.0 sections)
> (maint) Release prep 0.15.0

- .travis.yml
- lib/puppet_litmus.rb
Sending GithubAction info to honeycomb
> (IAC-490) Add CI checks and metadata information of github action

- lib/puppet_litmus/rake_helper.rb
> (IAC-658) suppress libhoney warning

- lib/puppet_litmus/puppet_helpers.rb
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- puppet_litmus.gemspec
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
Bolt v2 has some internal changes that we need to consume. This commit fixes all code references to Bolt v1 structures and names.
This closes #252.
Rebased-By: @DavidS 
All-Complaints-To: @DavidS
> (feat) move to using bolt v2

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Validation PRs:
https://github.com/puppetlabs/puppetlabs-motd/pull/300
https://github.com/puppetlabs/puppetlabs-package/pull/191
https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/132
> Release prep for 0.18.1

- lib/puppet_litmus/rake_helper.rb
This adds `raise_bolt_errors` to all remaining boltspec calls that didn't have one yet.
> Catch more errors in rake_helpers

- .travis.yml
- Gemfile
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
* move around some code for better logical grouping
* improve some YARD developer docs
* make travis faster
* produce better output on travis
* cleanup after dependabot
> (maint) various cleanups

- .travis.yml
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
This PR also contains some maintenance changes to improve CI and developer documentation.
> install_module: update module_repository default use to puppet's default

- .travis.yml
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- puppet_litmus.gemspec
- spec/lib/puppet_litmus/rake_tasks_spec.rb
> Fix install_modules_from_directory symlink handling

- puppet_litmus.gemspec
Reverts puppetlabs/puppet_litmus#297
Work is being tracked here: IAC-896
> (IAC-896) - Revert "(IAC-825) - Adding net-ssh 5 dependent gems"

- lib/puppet_litmus/puppet_helpers.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
This commit adds a helper to upload a string variable as a file to a
target host.
This prevents the current requirement to use the manifest_file helper
and then a separate shell command to move the file to desired
destination path on the target host.
Closes: #323
> Add write_file helper

- lib/puppet_litmus/rake_tasks.rb
Temporarily increase retry count to something ridiculous to test the limits.
> Increase retry count after agent installation

- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
Closes: https://github.com/puppetlabs/puppet_litmus/pull/337
> Try to fix the path on puppet version failure

- lib/puppet_litmus/rake_tasks.rb
As of now install_agent will print the config output
> (maint) set debug to print config results

- lib/puppet_litmus/puppet_helpers.rb
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
This is to align this with the conversation and changes in https://github.com/honeycombio/buildevents/pull/74
> Update honeycomb trace ENV var to new name

- spec/spec_helper.rb
The unit tests should be failing, if checks are green then this is not the fix i was looking for.
> (maint) But will it fail?

- spec/spec_helper.rb
Reverts puppetlabs/puppet_litmus#360
> Revert "(maint) But will it fail?"

- lib/puppet_litmus/rake_tasks.rb
Showing my working 
```
➜  puppetlabs-ntp git:(integration) ✗ export DEBUG=true
➜  puppetlabs-ntp git:(integration) ✗ bundle exec rake litmus:install_agent
install_agent
Git remote for spec/fixtures/modules/facts has changed, recloning repository
Git remote for spec/fixtures/modules/puppet_agent has changed, recloning repository
Git remote for spec/fixtures/modules/augeas_core has changed, recloning repository
Git remote for spec/fixtures/modules/stdlib has changed, recloning repository
Git remote for spec/fixtures/modules/provision has changed, recloning repository
Cloning into 'spec/fixtures/modules/provision'...
Cloning into 'spec/fixtures/modules/facts'...
Cloning into 'spec/fixtures/modules/augeas_core'...
Cloning into 'spec/fixtures/modules/puppet_agent'...
Cloning into …
```
> (maint) improve readability of agent install task

- lib/puppet_litmus/rake_helper.rb
> (maint) better UX for connectivity check task

- lib/puppet_litmus/puppet_helpers.rb
Closes: https://github.com/puppetlabs/puppet_litmus/pull/377
> Isolate puppet_helpers workaround for windows os family

- lib/puppet_litmus/puppet_helpers.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
The removal of any offensive or inappropriate terminology from the code base.
> (IAC-1442) - Removal of Inappropriate Terminology

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Testing against the modules prior to the release
https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/192
https://github.com/puppetlabs/puppetlabs-package/pull/250
https://github.com/puppetlabs/puppetlabs-motd/pull/409
> (maint) Release prep v0.26.3

- lib/puppet_litmus/inventory_manipulation.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
Updated the tests with the latest changes in litmus
> (maint) update failing tests

- exe/matrix_from_metadata_v2
OS not yet supported by the Google Cloud Platform, will we re-added when it is
> (FM-8922) Disable Support for Windows 2022

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Mistake was made on last release.
> (maint) Release prep v0.34.3

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/release_prep.yml
This PR implements the reusable workflows for this gem.
> (CONT-703) - Implement reusable workflow

- Gemfile
- Rakefile
- puppet_litmus.gemspec
This commit aims to map the dependencies of this RC of puppet_litmus to the RCs of other gems that are dependencies of puppet_litmus
> (CONT-806) Mapping RC dependencies

- docs/md/content/litmus-concepts.md
- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/puppet_helpers.rb
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- puppet_litmus.gemspec
Removing all leftover traces of Honeycomb from the codebase as we are no longer implementing it.
> (CONT-933) Remove Honeycomb

- .github/pull_request_template.md
Adding Community Pull Requests template for tools
> ((CONT-990) - Adding Community Pull Requests template for tools

- README.md
> (maint) - fix readme typo

- README.md
> (maint) - README updates

- docs/md/content/usage/commands/litmus-core-commands.md
(CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.
pdk version: `3.0.0`
> pdksync - (CAT-343) Audit modules and tools for references to travis. Removed all needless references to travis.

- docs/md/content/litmus-concepts.md
- docs/md/content/usage/commands/command-reference.md
- docs/md/content/usage/commands/litmus-core-commands.md
- docs/md/content/usage/litmus-helper-functions.md
- docs/md/content/usage/testing/litmus-test-examples.md
- docs/md/content/usage/testing/running-acceptance-tests.md
Provide more relevant/up-to-date examples in the litmus documentation, which will be displayed on the team site.
> (CAT-1333) - Use more relevant examples in docs

- exe/matrix_from_metadata_v3
- spec/exe/matrix_from_metadata_v3_spec.rb
Update v3 to target nightly images
> (FEAT) Update matrix_from_metadata_v3 to target puppetcore nightly

- spec/exe/matrix_from_metadata_v3_spec.rb
Signed-off-by: Gavin Didrichsen <gavin.didrichsen@gmail.com>
> (CAT-2456) Fix failing spec test
