- lib/puppet_litmus/rake_tasks.rb
Since the new value is already assigned to the variable, there's no need to replace the string in place.
> (maint) Do not use in place replacements

- lib/puppet_litmus.rb
- puppet_litmus.gemspec
This bolt version refactored and introduced bolt_spec/run. Pry shouldn't be a requirement at runtime.
https://github.com/puppetlabs/puppet_litmus/issues/66 is still a problem with this.
> Require bolt >= 0.21.4 and remove pry requirement

- lib/puppet_litmus/rake_tasks.rb
This task prints the supported OSes from metadata. It also splits off the parsing of metadata into a separate function so that could be tested standalone.
> Introduce a litmus:metadata task

- lib/puppet_litmus/rake_tasks.rb
This test has been tested with a local setup and I can confirm tests that should fail in travis now fail as the exit code is returned instead of returning 0 every time.
> (FM-7870) - Return with exit code 1 when tests fail

- puppet_litmus.gemspec
Versions of bolt lower than 1.13.1 cause dependency issues which result in the bundle completing. Limiting the lower version requirement to 1.13.1. This is related to cri and pdk dependencies.
> (FM-7579) - Limiting lower range of bolt dependency to 1.13.1

- lib/puppet_litmus/serverspec.rb
Under normal circumstances `tempfile` has not been required at the point where we call out to it meaning that people can get this error:
```
NameError:
uninitialized constant PuppetLitmus::Serverspec::Tempfile
```
This fixes that
> Added require for tempfile

- lib/puppet_litmus/serverspec.rb
Needed to add a --noop flag to apply_manifest due to the test conversion of puppetlabs-dsc.
This test uses --noop: https://github.com/puppetlabs/puppetlabs-dsc/blob/master/spec/acceptance/basic_functionality/puppet_apply_noop_dsc_manifest_spec.rb#L14
In order to successfully convert it to litmus I needed to add detection for --noop flag.
> (FM-8072) add noop flag detection to apply_manifest

- lib/puppet_litmus/rake_tasks.rb
The stdout result from the install PE command needs to be visible after install. The logs contain the one time password reset for the PE console.
> Update the install_pe experimental rake task

- lib/puppet_litmus/rake_tasks.rb
Prior to this commit the only way to pass additional provisioning params
to a provisioning task was via environment variables. This commit adds
an optional params hash to the provision.yaml definition, enabling a
user to pass an arbitrary set of keys to the provisioner.
These are transformed into environment variables as `LITMUS_param` where
the `param` is upcased. This will enable users of the vagrant provisioner
on windows to pass SMB username and passwords via the provision file
instead of typing them into the terminal.
The environment variables created during the run do not persist outside
of the ruby runspace.
> (FM-8178) Make params passable using provision.yaml

- .gitignore
- Gemfile
- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
Prior to this commit the `run_bolt_task` and `bolt_upload_file` methods
did not correctly emit stdout and stderr - `run_bolt_task` also swallowed
the exit codes of a run.
This commit updates both methods to correctly capture and emit the stdout
and stderr streams and ensures that a specific exit code for a task is
captured instead of being overwritten to `255`.
The reason for these updates is that the `run_task` and `upload_file`
methods leveraged by `run_bolt_task` and `bolt_upload_file` respectively
do not return the same structured results as `run_command` and
`run script` - namely, it does not return the `exit_code`, `stderr`, and
`stdout` key-value pairs in the `result` hash.
Instead the output, exit code, and error must be extricated from the
object to be passed along.
> (FM-8296) Ensure serverspec helpers emit correctly

- lib/puppet_litmus/serverspec.rb
This commit updates the logic for inventory hashes in the `run_bolt_task` method
to reuse the logic from other methods which returns `nil` for the inventtory
hash if the target is nil or localhost.
> (FM-8303) Ensure run_bolt_task works against localhost

- lib/puppet_litmus/rake_tasks.rb
This commit adds the `litmus:acceptance:serial` task which is a meta task
that calls the `litmus:acceptance:host_name:port` tasks one after another.
This allows for execution of tests which share dependencies, like the bolt
inventory file, and cannot run in parallel because of that.
> (feat) Add option to run acceptance in serial

- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
Prior to this commit it was not possible to pass hiera data to an apply call
during a litmus run. This commit adds the option to the apply_manifest method.
> (FM-8477) Add paramter to pass hiera config to apply calls

- lib/puppet_litmus/rake_tasks.rb
Prior to this commit the parameters loaded during provision_list
would be loaded as environment variables with LITMUS_ prepended.
This has been altered such that it does not alter the name of the
parameter except by upcasing for convention.
> (FM-8488) Correct param loading as env vars in provision_list

- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
The current implementation only detects failed catalog compiles. This is enough for very simple manifests, but misses errors when applying larger manifests. 
This PR uses detailed exitcodes to detect **ALL** errors. It also reports the stdout of the puppet run in a much better readable format when an error occurs.
> (feat) Better puppet error detection and better readable output

- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/rake_tasks.rb
- lib/puppet_litmus/serverspec.rb
- spec/lib/puppet_litmus/serverspec_spec.rb
Prior to this commit it was not possible to mock features when running
acceptance tests against localhost. This is because both specifying the
node name localhost causes bolt to ignore the inventory file and also
litmus passed an empty inventory file when calling the helpers against
localhost as the target node.
This commit makes some extensive additions and patches to the existing
behavior in order to enable mocking localhost during testing:
- It adds localhost_inventory_hash as a method in inventory_manipulation,
which will return a valid inventory hash containing only what bolt
needs to execute locally; it places the node litmus_localhost in
the local group and specifies the transport as local. This node CAN
NOT be named localhost or bolt will ignore the inventory file.
- It adds the …
> (FM-8342) Handle mocking of localhost

- lib/puppet_litmus/serverspec.rb
Before only the stdout was reported. This is confusing when a syntax error is in the puppet code.  The output is then empty, but the stderr reports the error
> (bugfix) Report both stderr and stdout when an error is detected

- lib/puppet_litmus.rb
- lib/puppet_litmus/spec_helper_acceptance.rb
This way, we just need to `require 'litmus_spec_helper_acceptance'` in the spec_helper_acceptance of every module
> (FM-8355) Add spec_helper_acceptance

- puppet_litmus.gemspec
The gemspec does not mention that this gem requires `parallel` and
`rspec`. Most users don't notice because those gems are already brought
in by other dependencies in the typical module's Gemfile.
The issue is when someone wants to leverage Litmus, but they aren't
doing modulet testing and want to avoid installing those other module
testing gems when they aren't needed, then the Litmus gem will fail to
install if `parallel` and `rspec` are not specifically added to the
Gemfile.
This change declares those two dependencies explicitly in the gemspec to
avoid this issue.
> (MAINT) Fix undeclared dependencies

- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
Previously the Litmus rake tasks loaded every single gem whether it was needed
or not. This bloats simple commans like "rake -T". As an example, on
puppetlabs-inifile, it takes 2 seconds to just list the available rake tasks.
While this number seems initially small, when combined with all the other rake
tasks a Puppet module developer brings in, any time saving is useful.
This commit changes the loading behaviour to require gems when needed, not all
at the top of the rake_tasks.rb file. Note that some helper files were also
modified for the same lazy loading behaviour as they are consumed by the rake
tasks.
> (maint) Lazily load gems in rake tasks

- lib/puppet_litmus/spec_helper_acceptance.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
This commit modifies the URI definition for the serverspec endpoint to only append the default port if one is not specified. Prior to this commit the implementation appended the default port regardless leading to a broken implementation with two ports specified.
> (MODULES-10115) Fix Windows endpoint declaration

- lib/puppet_litmus/spec_helper_acceptance.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
Prior to this commit the configuration for RSpec as defined in the spec_helper_acceptance included PuppetLitmus. This commit also extends the configuration with PuppetLitmus.
This enables test writers to use Litmus helpers such as `apply_manifest` or `run_shell` as describe subjects.
> (MODULES-10018) Extend RSpec config with PuppetLitmus

- lib/puppet_litmus/rake_tasks.rb
Our scope is to run acceptance tests in parallel mode to reduce the execution time.
Serial mode is not working as desired (using vmpooler provisioner is not implemented). Serial mode is not required
As a team (IA_Content team) we decided to cleanup the code and to remove it
> (FM-8779) - remove option to run acceptance tests using serial mode

- lib/puppet_litmus/rake_tasks.rb
This makes sure that the full error information is surfaced when something
goes wrong.
> Improve error reporting

- lib/puppet_litmus/rake_tasks.rb
```
pid 25464 exit 1
Failed on 15 nodes: ["syrupy-nod.delivery.puppetlabs.net, ubuntu-1804-x86_64", "liberal-ante.delivery.puppetlabs.net, debian-10-x86_64", "amen-shore.delivery.puppetlabs.net, ubuntu-1404-x86_64", "crumbly-gait.delivery.puppetlabs.net, debian-9-x86_64", "distal-lime.delivery.puppetlabs.net, oracle-7-x86_64", "mobile-secret.delivery.puppetlabs.net, sles-15-x86_64", "irate-guinea.delivery.puppetlabs.net, sles-11-x86_64", "fecund-pickaxe.delivery.puppetlabs.net, redhat-6-x86_64", "aloof-agnomen.delivery.puppetlabs.net, redhat-5-x86_64", "logical-clock.delivery.puppetlabs.net, scientific-7-x86_64", "tame-gelding.delivery.puppetlabs.net, centos-8-x86_64", "unlined-reducer.delivery.puppetlabs.net, scientific-6-x86_64", "jittery-cistern.delivery.puppetlabs.net, …
```
> (feat) check connectivity status, after testing completes

- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
During local testing I've found it very easy to forget to do the
spec_prep task when doing local testing. Given that there seems to be
no workflow I can think of where you would not want to do spec_prep
before calling litmus:acceptance:localhost, it seems to make sense to
just add it to the task.
> (MAINT) Ensure acceptance:localhost task also runs spec_prep

- Gemfile
- lib/puppet_litmus.rb
- lib/puppet_litmus/puppet_helpers.rb
- puppet_litmus.gemspec
Following changes with this PR
Pointed the gem to master(waiting for the release)
Add honeycomb-beeline gem to dependencies to litmus file
Updated code to capture modulename, travis/ appveyor information
Updated code to capture infm from run_bolt_task,bolt_run_script,bolt_upload_file,run_shell(for success and failure conditions)
Appveyor is not sending traces to the honeycomb (steps are different spec_prep then litmus:acceptance:parallel )
> (MODULES-10478) honeycomb integration to litmus

- .rubocop.yml
- lib/puppet_litmus/rake_helper.rb
Prior to this commit the `install_modules_from_directory` method failed on Windows nodes when calling `File.new` on a folder; this commit modifies the logic to instead grab the folder handle by `Dir.open` and use that instead.
The logic in the same method for deleting the build folder erroneously specified the builder instance which, at this point in the execution, has not been instantiated yet. This commit also modifies that logic to delete the target directory, which is where the built module tars are placed.
These fixes support but do not resolve #246 filed by @findmyname666, as the underlying problem around connections is caused by the removal of the version from the `inventory_hash` in `BoltSpec::Run`. For more information, see puppetlabs/bolt#1614.
> (GH-246) Fix install_modules_from_directory logic

- lib/puppet_litmus/util.rb
- spec/lib/puppet_litmus/util_spec.rb
Prior to this commit running PowerShell commands against target hosts during an acceptance test run required that the author both:
1. Wrap any PowerShell commands to ensure that they would be executed both  locally and remotely in PowerShell, as bolt localhost execution does not  run in PowerShell by default, and
2. Manually verify the interpolation of the code to be executed, accounting for passing from ruby to bolt to powershell/cmd and possibly beyond.
This commit adds a helper method to be available during acceptance test runs which allows an author to pass a string for the scriptblock they want to run in PowerShell; whatever that string evaluates to will be executed.
It does this first by base-64 encoding the command, enabling the use of the `EncodedCommand` flag when invoking …
> (MAINT) Add interpolate_powershell helper method

- .rubocop.yml
- Gemfile
- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/inventory_manipulation_spec.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
Previously this was guarded by the existence of a inventory.yaml file,
which could lead to errors when trying to chain operations:
```
~/git/puppetlabs-motd$ rm inventory.yaml
~/git/puppetlabs-motd$ bundle exec rake litmus:provision[docker,litmusimage/debian:9] litmus:install_agent litmus:install_module
Provisioning litmusimage/debian:9 using docker provisioner.[✔]
localhost:2223, litmusimage/debian:9
rake aborted!
NameError: undefined local variable or method `inventory_hash_from_inventory_file' for main:Object
/home/david/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/rake_tasks.rb:104:in `block (2 levels) in <top (required)>'
/home/david/gems/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => litmus:install_agent
(See full trace by running task …
```
> Make InventoryManipulation available to all rake tasks

- Gemfile
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- puppet_litmus.gemspec
- spec/lib/puppet_litmus/inventory_manipulation_spec.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
- spec/lib/puppet_litmus/version_spec.rb
- spec/spec_helper.rb
Block on release of the puppet-modulebuilder gem
---
Previously Litmus depended on the entire PDK gem, however it only used the
module building capability.  This commit
* Adds the puppet-modulebuilder gem into Litmus.
* Modified the rake helper to call the new Module Builder
* Modifies the gemspec to remove PDK and add the puppet-modulebuilder gem
---
TODO
> (GH-234) Remove PDK dependency

- appveyor.yml
- lib/puppet_litmus/inventory_manipulation.rb
As it turned out PowerShell does not report errors from subcommands as errors by default.
> (maint) make sure that errors in the acceptance tests fail; fix code to actually pass

- lib/puppet_litmus.rb
- lib/puppet_litmus/honeycomb_utils.rb
- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/puppet_helpers.rb
- lib/puppet_litmus/rake_helper.rb
Fixes #269, the use-case of supplying your own inventory.yaml without extra attached facts.
This also reverts the ugly addition to the `localhost_inventory_hash`, since that is not needed anymore.
> (IAC-660) make the platform fact optional

- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
Closes #259 
This change will allow the user to pass a private forge repository when running:
* rake install_module
* rake reinstall_module
* rake install_modules_form_directory
* rake provision_install
> Allow users to install modules form a private forge repository

- .travis.yml
- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
Fixes #246, fixes #270, fixes #250.
Core bits are the moving of the `target_dir` clean up in `build_modules_in_folder` and the general cleanup by re-using `build_module`, `upload_file` and `install_module` instead of duplicating the implementations.
> Improve rake task install_module and install_modules_from_directory

- .travis.yml
- lib/puppet_litmus/rake_helper.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
This makes `litmus:install_module` much safer as it ensures that it actually updates the module on the target systems. Previously it would have just failed quietly.
> (IAC-187) force installing modules

- .travis.yml
- lib/puppet_litmus/rake_helper.rb
Based on the work in #247 and a bug report in internal slack add testing for tear_down.
> Fix missing require in `litmus:tear_down`

- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
At some points we were still using bolt v1 hash keys and were not accessing
the correct information. This changes all uses of `'node'` to `'target'`
to address this.
> Use 'target' instead of 'node' in bolt result hashes

- lib/puppet_litmus/rake_helper.rb
Fixes #295 
Minor fix to the error message that is emitted when `puppet module install` fails
Before:
```
$ pdk bundle exec rake litmus:install_modules_from_directory
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.15.0
Building
Installing
rake aborted!
Installation of package #<File:0x00007fe30f31cb40> failed.
Errors: {"localhost:2222"=>"The command failed with exit code 1"}
```
After:
```
$ pdk bundle exec rake litmus:install_modules_from_directory
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.15.0
Building
Installing
rake aborted!
Installation of package puppetlabs-facts-1.0.0.tar.gz failed.
Errors: {"localhost:2222"=>"The command failed with exit code 1"}
```
> Log the filename instead of the file object when install fails

- puppet_litmus.gemspec
Placing net-ssh 5 dependent gems into the gemspec. This means they are added in 1 place rather than in all modules.
> (IAC-825) - Adding net-ssh 5 dependent gems

- lib/puppet_litmus/puppet_helpers.rb
- lib/puppet_litmus/rake_helper.rb
Using `/tmp` as upload target meant that `install_module` and
`create_manifest_file` would not work with windows SUTs, which do
not have that directory.
This changes those methods to not use any directory, dumping files
into the default user's home directory instead.
Fixes: #249
> Use default working directory for all uploads to SUTs

- lib/puppet_litmus/rake_helper.rb
This change makes errors from multiple hosts easier readable
> Improve bolt error formatting

- CHANGELOG.md
- Rakefile
- lib/puppet_litmus/version.rb
* bugfix-only release
* new changelog entry for 0.18.3
* verified that the FM-7963 fix was in 0.5.0, not 0.2.0
> (IAC-874) Release prep 0.18.3

- lib/puppet_litmus/spec_helper_acceptance.rb
> Ignore stderr of serverspec commands by setting request_pty to false

- lib/puppet_litmus/rake_helper.rb
In some cases when setting up litmus, `PuppetLitmus::VERSION`
is not defined, even though it is required at the start of the
file.
To avoid issues like #311, add a safety check here.
Fixes: #311
> Protect version reporting from undefined-ness

- .travis.yml
This change unrolls the test matrix to cover testing with
ruby 2.7 without duplicating the rubocop job.
> (IAC-859) Add testing with ruby 2.7

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Tests
https://github.com/puppetlabs/puppetlabs-motd/pull/317
https://github.com/puppetlabs/puppetlabs-package/pull/204
https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/143
ReleaseChecks
`Finished in 4 minutes 19.6 seconds (files took 13.07 seconds to load)
8 examples, 0 failures
pid 3176 exit 0
Successful on 4 nodes: ["unmeshed-havoc.delivery.puppetlabs.net, win-2012r2-x86_64", "thick-micelle.delivery.puppetlabs.net, win-2016-core-x86_64", "salty-toolmaker.delivery.puppetlabs.net, win-2019-core-x86_64", "gold-liter.delivery.puppetlabs.net, win-2008r2-x86_64"]
➜  puppetlabs-scheduled_task git:(pdksync_releaseprep0184)`
`Successful on 24 nodes: ["richest-break.delivery.puppetlabs.net, centos-6-x86_64", "sinewy-alfresco.delivery.puppetlabs.net, redhat-6-x86_64", …
> (IAC-896) Release Prep 0.18.4 

- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
Puppet Litmus is being used on servers that do not external access to the internet, we get errors when trying to run the Puppet Litmus Task **_install_module_**.  This ultimately executes _**puppet module install**_ to install the module which then looks to install module dependencies from Puppet Forge which fails.  To get around this we have tried using the Rake Task **_install_modules_from_directory_**, which also fails as this calls the module_install helper function as above, recusviely for all modules in the specified directory giving the same error.
I have added the optional parameter ignore_dependencies to the install_module function and the rake tasks that call it.  If the ignore_dependencies parameter is set to true then the switches --ignore-dependencies --force are added to the …
> Add optional ignore_dependencies parameter to install_module function

- lib/puppet_litmus/rake_helper.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
When building a module it currently looks like this:
Building '/Users/paula/workspace/puppetlabs-accounts/puppetlabs-accounts' into '/Users/paula/workspace/puppetlabs-accounts/puppetlabs-accounts/pkg''
> (maint) - Removing extra single quote

- .travis.yml
- appveyor.yml
- exe/matrix_from_metadata
- lib/puppet_litmus/puppet_helpers.rb
- puppet_litmus.gemspec
The `matrix_from_metadata` executable supports creating a platform
matrix for the new cloud-ci project based off the `metadata.json`
in the current module.
> Calculate github actions job matrix from metadata.json; fix frozen-string modification in puppet_output

- exe/matrix_from_metadata
See https://cloud.google.com/compute/docs/images#image_families and `gcloud compute images list`.
> simplify GCP images to use family names

- lib/puppet_litmus/rake_tasks.rb
Validates that puppet command is usable in the environment after a successful return from the agent install task run.
> Add validation check after agent install

- exe/matrix_from_metadata
The windows-2016 core image seems to have a transient failures in setting up the environment after a Puppet Agent 6 install
On boot-up there seems to be a COM+ issue in the EventLog:
> Use default windows-2016 server image

- lib/puppet_litmus/rake_tasks.rb
Currently when `CI=true bundle exec rake 'litmus:acceptance:parallel'` is ran it returns `" "`. 
This change means it now returns the node name and OS information. 
Example: 
`CI=true bundle exec rake 'litmus:acceptance:parallel'`
`Successful on 1 nodes: ["localhost:2227, litmusimage/oraclelinux:6"]`
`bundle exec rake 'litmus:acceptance:parallel'`
`Successful on 1 nodes: ["machine_name.puppet, centos-7-x86_64"]`
`CI=true bundle exec rake 'litmus:acceptance:parallel'`
`Failed on 1 nodes: ["localhost:2227, litmusimage/oraclelinux:6"]`
`bundle exec rake 'litmus:acceptance:parallel'`
`Failed on 1 nodes: ["machine_name.puppet, centos-7-x86_64"]`
Fixes #326
> (GH-326) - Return node name when testing is complete

- lib/puppet_litmus/rake_helper.rb
- lib/puppet_litmus/rake_tasks.rb
Request for a review.
configure_path function always returns multiple hashes in an array hence it throws the error while accessing change['status'] which doesn't exists
inventory_hash['groups'].select { |group| group['name'] == 'ssh_nodes' }.size.zero? always returns value greater than zero if the targets is empty so adding the following condition to return the group where targets are not empty.
> (maint) fix install_agent error

- exe/matrix_from_metadata
This reverts commit a3075ed858a34742e50e6570bdc536c6e1b5bc42.
> Revert "Use puppet 7 collection in acceptance test matrix"

- CHANGELOG.md
- lib/puppet_litmus/version.rb
Testing has been carried out and can be found in the following PRs: 
- https://github.com/puppetlabs/puppetlabs-accounts/pull/345
- https://github.com/puppetlabs/puppetlabs-java_ks/pull/340
- https://github.com/puppetlabs/puppetlabs-acl/pull/217
Additional testing on puppet7 has been carried out on the following images:
['redhat-7-x86_64', 'redhat-8-x86_64', 'sles-15-x86_64', 'sles-15-x86_64',]
['win-2012r2-x86_64', 'win-2016-core-x86_64', 'win-2019-core-x86_64', 'win-10-pro-x86_64']
> (IAC-1258) 0.19.0 Release Prep

- lib/puppet_litmus/rake_helper.rb
The docker_ext provisioner support's having extra cli parameters. This support has been lost in the caller. This PR reimplements this.
> Fix append_cli parameters

- lib/puppet_litmus/rake_helper.rb
- puppet_litmus.gemspec
This is based on the similar snippet in [rspec_honeycomb_formatter](https://github.com/puppetlabs/rspec_honeycomb_formatter/blob/e991d4464bb0a1e4969f53469a5c0718c43b061e/lib/rspec_honeycomb_formatter.rb#L19-L28)
> honeycomb: Improve capturing exitstatus in the process_span

- exe/matrix_from_metadata
This PR adds the ability for `matrix_from_metadata` to generate the agent collections portion of the test matrix from the module's `metadata.json`. This way, modules that don't support certain Puppet versions won't have tests run against those versions.
This supersedes #356.
> Add dynamic agent collections to test matrix generation

- lib/puppet_litmus/rake_tasks.rb
End users are only used to seeing output when using litmus if something
goes wrong. Setting so that the additional information can only be seen
when DEBUG=true is set.
> (IAC-1287) - Only log errors in debug mode

- lib/puppet_litmus/rake_tasks.rb
End users are only used to seeing output when using litmus if something
goes wrong. Setting so that the additional information can only be seen
when DEBUG=true is set.
This is #366 rebased and fix'er'upped.
> (IAC-1287) Only log transient provisioning errors in debug mode

- lib/puppet_litmus/rake_helper.rb
The `append_cli` option was only used by the `docker_exp` provisioner. The `docker` provisioner used `docker_run_opts` in the vars. PR https://github.com/puppetlabs/provision/pull/151 adds the changes so the `docker` and `docker_exp` both use `docker_run_opts` for passing options to the docker command.
> Remove optional parameter append_cli from provision api

- lib/puppet_litmus/puppet_helpers.rb
Alter the `apply_manifest` helper method to utilize the litmus `run_script` command, via the existing `bolt_run_script` helper method, instead of the original litmus `run_command` in order to sidestep a bug surrounding the retrieval of exit codes.
Windows requires some special code in order to properly retrieve the exit codes from within powershell scripts.
> (IAC-1365) - Workaround bolt/windows/exitcode bug

- lib/puppet_litmus/inventory_manipulation.rb
`version` option in Bolt `inventory.yaml` is deprecated, this removes the version check and version output in the generated inventory
Closes #375
> Remove deprecated version from bolt inventory

- exe/matrix_from_metadata
RHEL6 is out of public support and we want to stop testing against it.
> Remove rhel6 from all tests

- lib/puppet_litmus/puppet_helpers.rb
Without this change errors in the first `apply_manifest()` would not report
errors from `puppet apply`.
> Ensure that first-order failures in idempotent_apply get reported

- .gitignore
- exe/matrix_from_metadata_v2
Generate a `spec_matrix` output which will be used by the PR and Nightly workflows (see https://github.com/puppetlabs/pdk-templates/pull/372) to generate spec test matrixes.
See also:
https://github.com/puppetlabs/puppetlabs-testing/pull/352
https://github.com/puppetlabs/pdk-templates/pull/372
> (IAC-1307) Generate spec test matrix

- README.md
- lib/puppet_litmus/inventory_manipulation.rb
- Renaming the inventory.yaml file to litmus_inventory.yaml
- Relocating file from the module root directory to /spec/fixtures/
- Removal of vmpooler as it is deprecated
The point in this change is to avoid running tests on a live production system by accident.
This piece of work includes changes in multiple places. 
1. pdk-templates: https://github.com/puppetlabs/pdk-templates/pull/414
2. puppet_litmus: https://github.com/puppetlabs/puppet_litmus/pull/396
3. provision module: https://github.com/puppetlabs/provision/pull/161
The follow PR is testing out my changes: https://github.com/puppetlabs/puppetlabs-testing/pull/353
> (GH-380) Moving inventory.yaml to /spec/fixtures/litmus_inventory.yaml

- lib/puppet_litmus/puppet_helpers.rb
The new inventory path(`spec/fixtures/litmus_inventory.yaml`) should be used by all related functions, such as `bolt_upload_file`, `run_shell` and `apply_manifest`
> (bugfix) Update inventory path

- CHANGELOG.md
- lib/puppet_litmus/version.rb
inventory path was missed in the helper functions.
> (maint) Release prep v0.26.2

- lib/puppet_litmus/rake_tasks.rb
This update the default inventory.yaml file location in rake_tasks
Currently bolt team is also seeing the same error as that of package/reboot and service modules.
Test against the package/service/reboot module
https://github.com/puppetlabs/puppetlabs-package/pull/250
https://github.com/puppetlabs/puppetlabs-package/actions/runs/744679858
https://github.com/puppetlabs/puppetlabs-service/pull/182
https://github.com/puppetlabs/puppetlabs-service/pull/182/checks?check_run_id=2333307663
https://github.com/puppetlabs/puppetlabs-reboot/pull/294
https://github.com/puppetlabs/puppetlabs-reboot/actions/runs/744715641
> (bug) update the default inventory.yaml file location in rake_tasks

- puppet_litmus.gemspec
This updates the requirement for the `bolt` gem so the 3.x series can be
used.
> (maint) Update bolt requirement to include 3.x

- lib/puppet_litmus/rake_helper.rb
Due to recent changes the setup time for windows machines on GCP has increased and so the timeout limit needs to be raised accordingly.
> (maint) - Increase the connection timeout limit

- lib/puppet_litmus/puppet_helpers.rb
- spec/lib/puppet_litmus/puppet_helpers_spec.rb
Added a possibility to pass options to `idempotent_apply`. Without this change, developers can't use `idempotent_apply` if they want to specify a custom hiera config or a debug option.
> Added options to idempotent_apply

- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/puppet_helpers.rb
- requirements.md
- spec/lib/puppet_litmus/inventory_manipulation_spec.rb
- spec/support/inventory.rb
- spec/support/inventorytesting.yaml
(ISSUE 418) Accept a Target in Litmus Functions
This change will allow users to specify a target for each invocation of
a Litmus Puppet Helper. Specifying a target will not affect the current
value of the `ENV['TARGET_HOST']` variable.
Targets can be specified by using strings or symbols. Targets can be:
1. The name of a role assigned to a target via the `vars => roles` hash
of the target.
2. The name of a group in the inventory
3. The name of a specific target URI
The roles key in the inventory can be
1. Called either `Role` or `Roles`
2. Can have a single role `role: webserver` or an array:
```
roles:
- IIS
- Webserver
- Frontend
```
3. Values are searched in a case insensitive manner such that
`'webserver' == 'Webserver'`
Closes #418
Co-authored-by: Daniel Carabas …
> Allow Litmus Functions to accept a target

- exe/matrix_from_metadata_v2
OS is now support on the GCP so can be re-enabled
> (FM-8922) Re-enable support for Windows 2022

- README.md
- docs/md/content/about.md
- docs/md/content/litmus-concepts.md
- docs/md/content/usage/_index.md
- docs/md/content/usage/commands/_index.md
- docs/md/content/usage/commands/command-reference.md
- docs/md/content/usage/commands/litmus-core-commands.md
- docs/md/content/usage/converting-modules-to-use-Litmus.md
- docs/md/content/usage/litmus-helper-functions.md
- docs/md/content/usage/testing/_index.md
- docs/md/content/usage/testing/litmus-test-examples.md
- docs/md/content/usage/testing/running-acceptance-tests.md
- docs/md/content/usage/tools-included-in-Litmus.md
- docs/md/go.mod
- docs/md/md.go
This PR aims to migrate the litmus documentation from https://github.com/puppetlabs/litmus to the CAT team site.
This PR includes:
- Introduction of markdown files containing litmus documentation
- Addition of folders to store the markdown files.
- Introduction of go module for hugo/doc integration
> (CONT-177) - Restructuring of Documentation

- lib/puppet_litmus/rake_tasks.rb
Prior to this commit `litmus::acceptance` would check for the existance of litmus_inventory before building the `parallel` task.
If the file is not present then the task would not be build and not available in the list of tasks (`bundle exec rake --tasks`). It appears that tasks are only evaluated at Runtime.
This causes an issue when calling tasks sequentially inside a task via the api. In this particular case, the litmus_inventory file is only present after the provision task has executed. This means that the task list would have already been built without the acceptance task.
This would result in the following error:
`Don't know how to build task 'litmus:acceptance:parallel' (see --tasks)`
This commit removes the check so that the task can always be built. Checking for the existance of …
> (CONT-193) Always build parallel task

- exe/matrix_from_metadata_v2
Prior to this PR, litmus would provision a windows-2019-core image when performing testing against windows 2019 machines. This caused failures on and blocks part of the essential testing on the sqlserver module, with this error 
"The following error occurred:
You have selected a feature that is not supported on Windows Server Core."
The same tests pass on the other non-core windows machines.
This PR aims to update the windows-2019 image used, to a different windows 2019 image in GCP. ([here](https://console.cloud.google.com/compute/imagesDetail/projects/gce-uefi-images/global/images/windows-server-2019-dc-v20200609?orgonly=true&project=ia-content&supportedpurview=project))
> (maint) - Update windows 2019 image

- puppet_litmus.gemspec
This PR pins the r10k gem to 3.15.1 so that we do not hit dependency issues with gettext-setup and earlier versions of puppet.
This pin can probably be removed once puppet 6 has been fully retired.
> (CONT-712) Pin r10k gem

- exe/matrix_from_metadata_v2
Although we are dropping support for 6 we do not yet want to remove it from the generator as the removal of support will be a process and not an immediate action.
> (maint) Return Puppet 6 to matrix_from_metadata_v2

- puppet_litmus.gemspec
r10k pin required for Puppet 6
Must be removed for Puppet 8
> (CONT-828) Unpin r10k

- exe/matrix_from_metadata_v2
- spec/exe/matrix_from_metadata_v2_spec.rb
After the realease of Puppet 8 there seems to be some confusion with bundler causing it to pull older versions of Puppet 7.
This breaks CI.
This change forces puppet_maj_version == 7 to pull ~> 7.24.
> (MAINT) Force newer Puppet 7 Gem

- spec/lib/puppet_litmus/rake_tasks_spec.rb
updates the test case ` expect { Rake::Task['litmus:provision'].invoke('docker', 'centos:7') }.to output(expected_output).to_stdout` to ` expect { Rake::Task['litmus:provision'].invoke('docker', 'centos:7') }.to output(/{#{expected_output}/).to_stdout` as these tests were wrongly showing as failures.
> (maint) - update litmus:provision spec test

- exe/matrix_from_metadata_v2
- lib/puppet_litmus/rake_helper.rb
- spec/exe/matrix_from_metadata_v2_spec.rb
This PR adds the ability to override the default provider for the litmus images from docker to the provision_service, by supplying the `--provision-service` flag.
It also adds  the ability to supply a custom matrix (supplied as a file path), so the user can define their images, providers and labels used by matrix_from_metadata_v2. This can be done by passing the `--custom-matrix /path/to/matrix.json` argument.
This PR also removes the unnecessary `provision::` prefix from the provisioner, to prevent this error being continuously thrown:
`Unsupported provisioner 'provision::docker', try abs/docker/docker_exp/provision_service/vagrant/vmpooler`
Closes https://github.com/puppetlabs/puppet_litmus/issues/453
> (FEAT) - Add ability to supply a custom matrix and override default provisioner

- README.md
> (CONT-1200) - Add readme section for custom-matrix flag

- lib/puppet_litmus/rake_helper.rb
If no provisioner fact is present, skip tearing down and move on to next node.
Fixes https://github.com/puppetlabs/puppet_litmus/issues/421
> (CONT-1243) - Skip tear_down if no provisioner found

- lib/puppet_litmus/rake_helper.rb
This PR fixes an incompatibility issue with windows hosts and tty spinner.
Fixes https://github.com/puppetlabs/puppet_litmus/issues/144
> (CAT-1249) - Fix Spinner on Windows Hosts

- .rubocop_todo.yml
- lib/puppet_litmus/rake_tasks.rb
We have seen many times the PR CI is gets failed due to Connectivity check Timeout which lead to failure for the workflow, but the same can be successful if we retries.
So adding 3 retries whenever there is timeout failure.
- N/A
- N/A
> (CAT-1241) - Adding retry when provision failed with Timeout

- lib/puppet_litmus/rake_helper.rb
This PR fixes an issue where the puppet agent binary was not present on the secure path of the vagrant boxes, so subsequent puppet operations would fail.
It utilises the already present provision::fix_secure_path task in order to make the puppet agent binary accessible to all sudo users on the box, in most cases vagrant.
Fixes https://github.com/puppetlabs/provision/issues/225
> (CAT-1265) - Fix agent install on vagrant boxes

- .rubocop_todo.yml
- exe/matrix_from_metadata
- exe/matrix_from_metadata_v2
- spec/exe/fake_metadata.json
- spec/exe/matrix_from_metadata_v2_spec.rb
Agent Team have certified puppet agent with FOSS RHEL-9-ARM so we need to add for module testing as well.
N/A
> (CAT-1521) - Adding new OS RHEL-9 ARM

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- README.md
- docs/custom_matrix.json
- exe/matrix_from_metadata_v2
- spec/exe/fake_metadata.json
- spec/exe/matrix_from_metadata_v2_spec.rb
This PR adds a new constant `ARM_IMAGE_TABLE` which contains viable arm architecture images in GCP.  Now whenever rhel-9 is listed as a supported OS in a modules metadata, both the intel and arm GCP image details are returned.
Have opted for bugfix label as fixes regression in https://github.com/puppetlabs/puppet_litmus/pull/530. We cannot specify `arm` explicitly in the metadata.json.
https://perforce.atlassian.net/browse/CAT-1545
Verified with metadata.json containing `rhel-9` that both the rhel-9 intel and rhel-9-arm entries are returned:
```
matrix={"platforms":[{"label":"CentOS-6","provider":"docker","image":"litmusimage/centos:6"},{"label":"RedHat-8","provider":"provision_service","image":"rhel-8"},{"label":"RedHat-9","provider":"provision_service","image":"rhel-9"},{"label":"RedHat- …
```
> (CAT-1545) - Return RHEL-9 ARM images in matrix

- .rubocop_todo.yml
- exe/matrix_from_metadata_v2
- spec/exe/fake_metadata.json
- spec/exe/matrix_from_metadata_v2_spec.rb
Adding support for Ubuntu 22.04 ARM Operating System.
> (CAT-1522) - Adding support for Ubuntu 22.04 ARM OS

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
Following a recent team decision, we are implementing a Rubocop Upgrade moving the version from 1.48.1 to 1.50.0. This should be the final version until Puppet 7 is unsupported.
> (CAT-1688) Upgrade Rubocop

- lib/puppet_litmus/rake_tasks.rb
- spec/lib/puppet_litmus/rake_tasks_spec.rb
- spec/lib/puppet_litmus/util_spec.rb
* fixes no targets listed in `Installed <module> on ` message when install_module on all targets
* improve performance of install_module_from_directory
* fix install module targets by using the find_targets instead of the rake arg
> Minor install_module improvements

- exe/matrix_from_metadata
- exe/matrix_from_metadata_v2
Cleanup of no longer supported OS
> (BUGFIX) Remove CentOS 6 from `matrix_from_metadata`

- exe/matrix_from_metadata_v2
EOL, vendor repos do not work, and Puppet hasn't built agents for a long time
> drop Debian 9 stretch from matrix

- lib/puppet_litmus/spec_helper_acceptance.rb
This fixes running Serverspec tests against nodes created by the docker_exp provision task. Unlike the docker bolt transport, the Serverspec docker backend uses the docker API. Unfortunately it lacks support for modern docker contexts (notably ssh).
_Only applies to nodes created with the docker_exp provision task_
> use dockercli specinfra backend for docker_nodes

- Gemfile
- exe/matrix.json
- exe/matrix_from_metadata_v3
- lib/puppet_litmus/inventory_manipulation.rb
- lib/puppet_litmus/rake_helper.rb
- puppet_litmus.gemspec
Reverts puppetlabs/puppet_litmus#565
> Revert "(maint) Exclude breaking rubocop versions"

- exe/matrix_from_metadata_v2
- spec/exe/matrix_from_metadata_v2_spec.rb
When testing changes with workflows on a personal fork, acceptance tests always fail because provision_service hosts are always included. This PR automatically filters them if the owner isn't `puppetlabs`, and the GITHUB_REPOSITORY_OWNER variable is set.
> automatically filter provision_service from matrix

- exe/matrix.json
- exe/matrix_from_metadata_v2
> (FEAT) - Add debian 12 & alma/centos/rocky 9 to matrix_from_metadata v2 & v3

- lib/puppet_litmus/rake_tasks.rb
There is a bug in the 'install_agent' task.
It is supposed to install the agent on a host (a VM or a docker container) using bolt and then add the 'puppet-agent' feature to the host in the litmus_inventory file.
Bolt returns the SHA ID of the container instead of the localhost URI after it installs the agent. The feature is added through the add_feature_to_node() method.
The last parameter of the method is being sent as result["target"]. This is fine in the case of VMs since its their IPv4 address and the method is expecting just that.
But in case of docker containers it is their SHA container ID and the method expecting the localhost:{port} URI. This results in the feature not being added to the host.
Since bolt is returning the results in the same order it is provided the input …
> (CAT-2052) Pass target container URI instead of container SHA ID to add_feature_to_node() method

- exe/matrix_from_metadata_v3
- spec/exe/matrix_from_metadata_v3_spec.rb
This commit adds a feature to the `matrix_from_metadata_v3`  tool allowing users to pass the option `--pe-include` which will add Puppet Enterprise LTS versions to the collection matrix.
This is done by utilizing the `puppet_forge` gem to make a connection to the Forge API and retrieve a list of PE versions. 
The code in this commit will only add the LTS versions of PE to the collection matrix if the tool is passed the aforementioned option and the puppet version in the LTS falls within the supported range found in the metadata.
**Note**: Ideally this would add LTS and STS to the collection matrix. Once PE 2025.y is released, this could be easily updated to add the STS to the collection as well.
My team is currently unable to utilize this tool to test our modules against PE. As such we …
> (FEAT) Add PE to matrix_from_metadata_v3

- exe/matrix.json
- exe/matrix_from_metadata_v2
Add Ubuntu-24.04 (amd and arm) to matrix_from_metadata v2 and v3
> (feat) - Add Ubuntu-24.04 to matrix_from_metadata v2 and v3

- puppet_litmus.gemspec
puppet_litmus needs to be re-pointed to the latest bolt version 4.0.0 as it is currently pinned to the old.  This is breaking CI.  This PR fixes this.
Although all the CI tests are passing I did a manual verification of a puppet_litmus provision and test, which uses the underlying bolt.  See in comments
> Update to bolt 4

- README.md
- exe/matrix_from_metadata_v2
- exe/matrix_from_metadata_v3
- lib/puppet_litmus/rake_helper.rb
- spec/exe/matrix_from_metadata_v2_spec.rb
- spec/exe/matrix_from_metadata_v3_spec.rb
Installs puppet agent from public repos, as oppose to nightly.
Also adds the ability to supply a specific puppet version to the install_agent task.
> fix: update matrix_from_metadata v2/v3 to install from public repos

- exe/matrix_from_metadata_v2
Mark matrix_from_metadata_v2 as deprecated in prepartion of puppet_litmus v2.
This will show as a warning in the github actions output, see example: https://github.com/puppetlabs/puppetlabs-peadm/actions/runs/14771597838/job/41472575236?pr=590#step:5:10
> breaking: mark matrix_from_metadata_v2 as deprecated in output

- README.md
- lib/puppet_litmus/rake_helper.rb
- spec/lib/puppet_litmus/rake_helper_spec.rb
This PR adds support for installing puppetcore agents through the `litmus:install_agent` rake task.
To do this, you must supply a puppetcore collection to the rake task, and have exported your `PUPPET_FORGE_TOKEN` in the ENV.
> feat: add puppetcore agent installation support

- exe/matrix_from_metadata_v2
- exe/matrix_from_metadata_v3
- spec/exe/matrix_from_metadata_v2_spec.rb
- spec/exe/matrix_from_metadata_v3_spec.rb
Updates matrix_from_metadata v2/v3 to use puppetcore by default
See example ci run https://github.com/puppetlabs/puppetlabs-peadm/actions/runs/14776268433/job/41485188480 (unsigned SLES 12 package has been raised with RE)
> feat: use puppetcore by default in matrix_from_metadata

- spec/exe/matrix_from_metadata_v3_spec.rb
Bumps the expected PE LTS version return from matrix_from_metadata_v3 from 2023.8.0 to 2023.8.3 (just went LTS).
> (maint) - Bump expected PE LTS version in tests

- exe/matrix.json
Following an investigation on recent Almalinux 8 provisioning failures, it was found that there is a security policy issue that prevents ubuntu 24.04 runners from running the provisioning script for Almalinux
8. This commits defaults Almalinux 8 provisioning to always run on ubuntu 22.04 runners.
> (CAT-2416) Address almalinux 8 provisioning issues

- README.md
- exe/matrix_from_metadata_v3
- spec/exe/matrix_from_metadata_v3_spec.rb
Adds a command-line option to specify whether the latest agent build should be included in the matrix. This is due to the Mac and Windows puppet_agent install tasks requiring a specific version when installing.
This updates the passed back information to the below format:
```
matrix={
{"matrix":{"platforms":[
{"label":"CentOS-7","provider":"docker","arch":"x86_64","image":"litmusimage/centos:7","runner":"ubuntu-22.04"},
{"label":"CentOS-8","provider":"docker","arch":"x86_64","image":"litmusimage/centos:stream8","runner":"ubuntu-latest"},
{"label":"OracleLinux-7","provider":"docker","arch":"x86_64","image":"litmusimage/oraclelinux:7","runner":"ubuntu-22.04"},
{"label":"Scientific-7","provider":"docker","arch":"x86_64","image":"litmusimage/scientificlinux:7","runner":"ubuntu-22.04"}, …
```
> (CAT-2433) Adds option to return latest agent build

- exe/matrix.json
The matrix identifies RockyLinux by its short name 'Rocky'. Adjusting this name in a conditional to ensure ubuntu 22.04 usage during provisioning.
> (MAINT) Fix Rocky typo in matrix.json
